<?xml version="1.0" encoding="UTF-8"?>
<project>
  <modelVersion>4.0.0</modelVersion>

  <groupId>4b47833c-de54-49ae-a281-2585b364b81c</groupId>
  <artifactId>mule-common-utils-library</artifactId>
  <version>1.0.0</version>
  <packaging>jar</packaging>

  <name>mule-common-utils-library</name>
  <description>Mule Common Utils Library - DataWeave utilities</description>

  <properties>
    <mule.version>4.6.0</mule.version>
    <type>custom</type>
  </properties>

  <repositories>
    <repository>
      <id>anypoint-exchange-v3</id>
      <name>Anypoint Exchange</name>
      <url>https://maven.jp1.platform.mulesoft.com/api/v3/organizations/4b47833c-de54-49ae-a281-2585b364b81c/maven</url>
      <layout>default</layout>
    </repository>
    <repository>
      <id>mulesoft-releases</id>
      <name>MuleSoft Releases Repository</name>
      <url>https://repository.mulesoft.org/releases/</url>
    </repository>
  </repositories>

  <pluginRepositories>
    <pluginRepository>
      <id>mulesoft-releases</id>
      <name>MuleSoft Releases Repository</name>
      <url>https://repository.mulesoft.org/releases/</url>
      <snapshots><enabled>false</enabled></snapshots>
    </pluginRepository>
  </pluginRepositories>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <!-- classifier obligatorio para que Exchange reconozca el tipo -->
          <classifier>custom</classifier>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>2.7</version>
        <configuration>
          <skip>true</skip>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.mule.tools.maven</groupId>
        <artifactId>exchange-mule-maven-plugin</artifactId>
        <version>0.1.7</version>
        <inherited>false</inherited>
        <executions>
          <execution>
            <id>validate</id>
            <phase>validate</phase>
            <goals>
              <goal>exchange-pre-deploy</goal>
            </goals>
          </execution>
          <execution>
            <id>deploy</id>
            <phase>deploy</phase>
            <goals>
              <goal>exchange-deploy</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <distributionManagement>
    <repository>
      <id>anypoint-exchange-v3</id>
      <name>Anypoint Exchange</name>
      <url>https://maven.jp1.platform.mulesoft.com/api/v3/organizations/4b47833c-de54-49ae-a281-2585b364b81c/maven</url>
      <layout>default</layout>
    </repository>
  </distributionManagement>

</project>